language: objective-c
osx_image: xcode10.1
before_install:
  - gem install cocoapods --pre --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "DuoAPISwift.xcodeproj" -scheme "DuoAPISwift" -sdk "macosx10.13" build test | xcpretty
  - pod lib lint
